### ISSUE TITLE
ResourceExhaustedError in CNN/MNIST example (with GPU)

### ISSUE THREAD

**Issue by FMsunyh** [titu1994/tf-eager-examples#2]
Hi titu1994,
I got an issue when I run the code (05_resnet.py)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[60000,16,28,28] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:FusedBatchNorm]

Do you know how to solve this problem.
Also, I have set the batch_size of 2, but same error issue occur.

**Comment by titu1994** [comment]
It's a bug in TF eager, as far as I've found. I've mentioned a fix in the earlier examples, but basically use the private function model._set_inputs. 

If that doesn't work, then simply call the model on a single data point first to build all the tensors. Aka is model (dummy_x).

**Comment by FMsunyh** [comment]
Hi titu1994;
Thanks, it works for me.
